#define TRACE_POSTGRESQL_TRANSACTION_START(INT1) elog( DEBUG3, "Transaction start." );
#define TRACE_POSTGRESQL_TRANSACTION_START_ENABLED() (1)
#define TRACE_POSTGRESQL_TRANSACTION_COMMIT(INT1) elog( DEBUG3, "Transaction end." );
#define TRACE_POSTGRESQL_TRANSACTION_COMMIT_ENABLED() (1)
#define TRACE_POSTGRESQL_TRANSACTION_ABORT(INT1) elog( DEBUG3, "Transaction abort." );
#define TRACE_POSTGRESQL_TRANSACTION_ABORT_ENABLED() (1)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_RELEASE(INT1, INT2)
#define TRACE_POSTGRESQL_LWLOCK_RELEASE_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_WAIT_START(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_WAIT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_WAIT_DONE(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_WAIT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_CONDACQUIRE_FAIL_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_ENABLED() (0)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_LWLOCK_ACQUIRE_OR_WAIT_FAIL_ENABLED() (0)
#define TRACE_POSTGRESQL_LOCK_WAIT_START(INT1, INT2, INT3, INT4, INT5, INT6) elog( DEBUG3, "Lock wait start." );
#define TRACE_POSTGRESQL_LOCK_WAIT_START_ENABLED() (1)
#define TRACE_POSTGRESQL_LOCK_WAIT_DONE(INT1, INT2, INT3, INT4, INT5, INT6) elog( DEBUG3, "Lock wait done." );
#define TRACE_POSTGRESQL_LOCK_WAIT_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_PARSE_START(INT1) elog( DEBUG3, "Query parse start." );
#define TRACE_POSTGRESQL_QUERY_PARSE_START_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_PARSE_DONE(INT1) elog( DEBUG3, "Query parse end." );
#define TRACE_POSTGRESQL_QUERY_PARSE_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_REWRITE_START(INT1) elog( DEBUG3, "Queyr rewrite start." );
#define TRACE_POSTGRESQL_QUERY_REWRITE_START_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_REWRITE_DONE(INT1) elog( DEBUG3, "Query rewrite end." );
#define TRACE_POSTGRESQL_QUERY_REWRITE_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_PLAN_START() elog( DEBUG3, "Query plan start." );
#define TRACE_POSTGRESQL_QUERY_PLAN_START_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_PLAN_DONE() elog( DEBUG3, "Query plan end." );
#define TRACE_POSTGRESQL_QUERY_PLAN_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_EXECUTE_START() elog( DEBUG3, "Query execute start." );
#define TRACE_POSTGRESQL_QUERY_EXECUTE_START_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_EXECUTE_DONE() elog( DEBUG3, "Query execute end." );
#define TRACE_POSTGRESQL_QUERY_EXECUTE_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_START(INT1) elog( DEBUG3, "Query start." );
#define TRACE_POSTGRESQL_QUERY_START_ENABLED() (1)
#define TRACE_POSTGRESQL_QUERY_DONE(INT1) elog( DEBUG3, "Query done." );
#define TRACE_POSTGRESQL_QUERY_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_STATEMENT_STATUS(INT1)
#define TRACE_POSTGRESQL_STATEMENT_STATUS_ENABLED() (0)
#define TRACE_POSTGRESQL_SORT_START(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Sort start." );
#define TRACE_POSTGRESQL_SORT_START_ENABLED() (1)
#define TRACE_POSTGRESQL_SORT_DONE(INT1, INT2) elog( DEBUG3, "Sort done." );
#define TRACE_POSTGRESQL_SORT_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_READ_START(INT1, INT2, INT3, INT4, INT5, INT6, INT7) elog( DEBUG3, "Buffer read start." );
#define TRACE_POSTGRESQL_BUFFER_READ_START_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_READ_DONE(INT1, INT2, INT3, INT4, INT5, INT6, INT7, INT8) elog( DEBUG3, "Buffer read end." );
#define TRACE_POSTGRESQL_BUFFER_READ_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_FLUSH_START(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Buffer flush start." );
#define TRACE_POSTGRESQL_BUFFER_FLUSH_START_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_FLUSH_DONE(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Buffer flush end." );
#define TRACE_POSTGRESQL_BUFFER_FLUSH_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START(INT1)
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START()
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_SYNC_START_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE()
#define TRACE_POSTGRESQL_BUFFER_CHECKPOINT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_SYNC_START(INT1, INT2)
#define TRACE_POSTGRESQL_BUFFER_SYNC_START_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN(INT1)
#define TRACE_POSTGRESQL_BUFFER_SYNC_WRITTEN_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_SYNC_DONE(INT1, INT2, INT3)
#define TRACE_POSTGRESQL_BUFFER_SYNC_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Dirty buffer write start." );
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_START_ENABLED() (1)
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Dirty buffer write end." );
#define TRACE_POSTGRESQL_BUFFER_WRITE_DIRTY_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_DEADLOCK_FOUND() elog( DEBUG3, "Deadlock found." );
#define TRACE_POSTGRESQL_DEADLOCK_FOUND_ENABLED() (1)
#define TRACE_POSTGRESQL_CHECKPOINT_START(INT1) elog( DEBUG3, "Checkpoint start." );
#define TRACE_POSTGRESQL_CHECKPOINT_START_ENABLED() (1)
#define TRACE_POSTGRESQL_CHECKPOINT_DONE(INT1, INT2, INT3, INT4, INT5) elog( DEBUG3, "Checkpoint end." );
#define TRACE_POSTGRESQL_CHECKPOINT_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_START(INT1)
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE(INT1)
#define TRACE_POSTGRESQL_CLOG_CHECKPOINT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START(INT1)
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE(INT1)
#define TRACE_POSTGRESQL_SUBTRANS_CHECKPOINT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START(INT1)
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE(INT1)
#define TRACE_POSTGRESQL_MULTIXACT_CHECKPOINT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START()
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_START_ENABLED() (0)
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE()
#define TRACE_POSTGRESQL_TWOPHASE_CHECKPOINT_DONE_ENABLED() (0)
#define TRACE_POSTGRESQL_SMGR_MD_READ_START(INT1, INT2, INT3, INT4, INT5, INT6) elog( DEBUG3, "Smgr read from disk start." );
#define TRACE_POSTGRESQL_SMGR_MD_READ_START_ENABLED() (1)
#define TRACE_POSTGRESQL_SMGR_MD_READ_DONE(INT1, INT2, INT3, INT4, INT5, INT6, INT7, INT8) elog( DEBUG3, "Smgr read from disk end." );
#define TRACE_POSTGRESQL_SMGR_MD_READ_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_START(INT1, INT2, INT3, INT4, INT5, INT6) elog( DEBUG3, "Smgr write to disk start." );
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_START_ENABLED() (1)
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE(INT1, INT2, INT3, INT4, INT5, INT6, INT7, INT8) elog( DEBUG3, "Smgr write to disk end." );
#define TRACE_POSTGRESQL_SMGR_MD_WRITE_DONE_ENABLED() (1)
#define TRACE_POSTGRESQL_XLOG_INSERT(INT1, INT2)
#define TRACE_POSTGRESQL_XLOG_INSERT_ENABLED() (0)
#define TRACE_POSTGRESQL_XLOG_SWITCH()
#define TRACE_POSTGRESQL_XLOG_SWITCH_ENABLED() (0)
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START() elog( DEBUG3, "WAL buffer write start." );
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_START_ENABLED() (1)
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE() elog( DEBUG3, "WAL buffer write end." );
#define TRACE_POSTGRESQL_WAL_BUFFER_WRITE_DIRTY_DONE_ENABLED() (1)
